import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import '@/utils/axios.js'
import ReduxProvider from "@/store/ReduxProvider";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-50  text-gray-800 ${poppins.className}`}>
        <ReduxProvider>
            <Header />
          <div className="flex flex-col min-h-screen mt-12 bg-gray-50 m-auto w-full p-5 lg:max-w-5xl">
            {children}
            </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
